version: '3.8'
services:
  web:
    env_file: .env
    build:
      context: .
      dockerfile: dev.Dockerfile
    container_name: perfect_panel_web
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    volumes:
      - ./:/app
  mysql:
    image: mysql:latest
    container_name: perfect_panel_mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=perfect_panel
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10